# Generated by Django 5.2.6 on 2025-10-01 18:54

import django.db.models.deletion
import django.db.models.functions.text
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Numero do telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail completo', max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('cpf', models.CharField(max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Numero do telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail completo', max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('cnpj', models.CharField(max_length=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.pessoafisica')),
                ('tipoFuncionario', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
            bases=('pessoas.pessoafisica',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Numero do telefone', max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail completo', max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('tipoCliente', models.CharField(max_length=20)),
                ('pessoa_fisica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pf', to='pessoas.pessoafisica')),
                ('pessoa_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pj', to='pessoas.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
    ]
