# Generated by Django 5.2.6 on 2025-10-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pessoa_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pf', to='pessoas.pessoafisica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pessoa_juridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes_pj', to='pessoas.pessoajuridica'),
        ),
    ]
