# Generated by Django 5.2.6 on 2025-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ocupado', 'Ocupado'), ('vago', 'Vago')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VagaEstacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField()),
            ],
        ),
    ]
