# Generated by Django 5.2.6 on 2025-10-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Empresa', max_length=100)),
                ('cnpj', models.CharField(help_text='CNPJ da Empresa', max_length=14, unique=True)),
                ('endereco', models.CharField(help_text='Endereco da Empresa', max_length=200)),
                ('receita_mensal', models.DecimalField(decimal_places=2, help_text='Receita mensal da Empresa', max_digits=10)),
                ('despesa_mensal', models.DecimalField(decimal_places=2, help_text='Despesa mensal da Empresa', max_digits=10)),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Estacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('capacidade', models.PositiveIntegerField()),
                ('ocupadas', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('ocupado', 'Ocupado'), ('vago', 'Vago')], max_length=20)),
                ('valor_hora', models.FloatField(default=10.0)),
                ('funcionarios', models.ManyToManyField(blank=True, related_name='estacionamentos', to='pessoas.funcionario')),
            ],
        ),
    ]
