# Generated by Django 5.2.6 on 2025-09-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('estacionamento_app', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='funcionario_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='vagaestacionamento',
            name='estacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento_app.estacionamento'),
        ),
        migrations.AddField(
            model_name='vagaestacionamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.pessoafisica'),
        ),
    ]
