# Generated by Django 5.2.6 on 2025-09-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.pessoafisica')),
            ],
        ),
    ]
