# Generated by Django 5.2.6 on 2025-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Empresa', max_length=100)),
                ('cnpj', models.CharField(help_text='CNPJ da Empresa', max_length=14, unique=True)),
                ('endereco', models.CharField(help_text='Endereco da Empresa', max_length=200)),
                ('receita_mensal', models.DecimalField(decimal_places=2, help_text='Receita mensal da Empresa', max_digits=10)),
                ('despesa_mensal', models.DecimalField(decimal_places=2, help_text='Despesa mensal da Empresa', max_digits=10)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
