# Generated by Django 5.2.6 on 2025-10-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacionamento_app', '0001_initial'),
        ('pessoas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaEstacionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.FloatField(default=0.0)),
                ('estacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='estacionamento_app.estacionamento')),
                ('funcionario_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadias_entrada', to='pessoas.funcionario')),
                ('funcionario_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadias_saida', to='pessoas.funcionario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='veiculos.veiculo')),
            ],
        ),
    ]
